# Generated by Django 3.0.5 on 2020-04-02 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pj4', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeamMemeber',
            new_name='TeamMember',
        ),
    ]
