# Generated by Django 3.0.5 on 2020-04-02 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pj4', '0002_auto_20200402_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='need',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
