# Generated by Django 3.0.5 on 2020-04-03 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pj4', '0003_requests_need'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requests',
            name='number',
        ),
        migrations.AlterField(
            model_name='requests',
            name='phone_number',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
